from django.urls import path
from .views import index, viewsUser, viewsProducts, viewsOrders, viewsCart, viewsSales

urlpatterns = [
    path('', index.index, name='index'),
    path('register', viewsUser.register, name='register'),
    path('listProducts', viewsProducts.listProducts, name="listProducts"),
    path('login/', viewsUser.login, name='login'),
    path('logout/', viewsUser.logout, name='logout'),
    path('profile/', viewsUser.profile, name='profile'),
    path('product', viewsProducts.product, name='product'),
    path('addCart', viewsCart.addCart, name='addCart'),
    path('removeCart', viewsCart.removeCart, name='removeCart'),
    path('cart', viewsCart.listCart, name='listCart'),
    path('addProduct', viewsProducts.addProduct, name='addProduct'),
    path('addProductType', viewsProducts.addProductType, name='addProductType'),
    path('beforeCreateOrder', viewsOrders.beforeCreateOrder, name='beforeCreateOrder'),
    path('createOrder', viewsOrders.createOrder, name='createOrder'),
    path('listOrders', viewsOrders.listOrders, name='listOrders'),
    path('orderDetail', viewsOrders.orderDetail, name='orderDetail'),
    path('registerClient', viewsUser.registerClient, name='registerClient'),
    path('displayProductTypes', viewsSales.displayProductTypes, name='displayProductTypes'),
    path('createSales', viewsSales.createSales, name='createSales'),
    path('sales', viewsSales.sales, name="sales"),
    path('deleteSale', viewsSales.deleteSale, name="deleteSale"),
    path('listAllProducts', viewsProducts.listAllProducts, name="listAllProducts"),
    path('deleteProduct', viewsProducts.deleteProduct, name="deleteProduct"),
    path('updateProduct', viewsProducts.updateProduct, name="updateProduct"),
    path('getAllOrdersView', viewsOrders.getAllOrdersView, name="getAllOrdersView"),
    path('getAllOrdersByUser', viewsOrders.getAllOrdersByUser,name="getAllOrdersByUser"),
    path('getSoldsByPartner', viewsProducts.getSoldsByPartner, name="getSoldsByPartner"),
    path('getProductRequests', viewsProducts.listUnconfirmedProducts, name="getProductRequests"),
    path('confirmProduct', viewsProducts.confirmProduct, name="confirmProduct"),
    path('rejectProduct', viewsProducts.rejectProduct, name="rejectProduct"),
    path('confirmAllProducts', viewsProducts.confirmAllProducts, name="confirmAllProducts"),
    path('downloadProductsJsonFile', viewsProducts.downloadProductsJsonFile, name="downloadProductsJsonFile"),
    path('downloadProductsXMLFile', viewsProducts.downloadProductsXMLFile, name="downloadProductsXMLFile"),
    path('downloadUsersJsonFile', viewsUser.downloadUsersJsonFile, name="downloadUsersJsonFile"),
    path('downloadUsersXMLFile', viewsUser.downloadUsersXMLFile, name="downloadUsersXMLFile"),
    path('ordersRequests', viewsOrders.ordersRequests, name="ordersRequests"),
    path('acceptOrders', viewsOrders.acceptOrders, name="acceptOrders"),
    path('acceptAllOrders', viewsOrders.acceptAllOrders, name="acceptAllOrders"),
    path('ordersRequestDetails', viewsOrders.orderRequestDetails, name="orderRequestDetails"),
]
